/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a natural-language production request
         * @description Parses NL text (with `now` for TZ-aware "tomorrow" resolution),
         *     runs deterministic collision check, returns parsed slots + collision
         *     report. Idempotent on `idempotencyKey` (uuidv4).
         */
        post: operations["createRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reroute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a reroute to an alternative slot
         * @description Transactional move: release old hold, hold alternative, move crew/gear
         *     atomically. `hold_slot` re-checks inside the transaction; a stale
         *     alternative yields 409 STALE_ALTERNATIVE (E12).
         */
        post: operations["rerouteRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List slots for a calendar date */
        get: operations["listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent events for radar updates
         * @description SSE stream. Events: `slot:confirmed`, `collision`. Client reconnects
         *     with exponential backoff and falls back to polling GET /api/slots
         *     every 5s (E18).
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example stage
         * @enum {string}
         */
        ResourceType: "stage" | "gear" | "crew";
        /**
         * @example confirmed
         * @enum {string}
         */
        SlotStatus: "holding" | "confirmed" | "released";
        /** @description Canonical slot — field names frozen across TS/Zod/Pydantic. */
        Slot: {
            /** @example slot_abc123 */
            id: string;
            /** @example Project Atlas */
            production: string;
            resource_type: components["schemas"]["ResourceType"];
            /** @example stage-3 */
            resource_id: string;
            /**
             * Format: date-time
             * @description UTC datetime (ISO 8601, Z suffix)
             * @example 2026-09-06T06:00:00Z
             */
            start: string;
            /**
             * Format: date-time
             * @description UTC datetime (ISO 8601, Z suffix); must be > start (else 422 INVALID_INTERVAL)
             * @example 2026-09-06T18:00:00Z
             */
            end: string;
            status: components["schemas"]["SlotStatus"];
            /** @example req_123 */
            request_id: string;
            /** @example trace_abc123 */
            trace_id: string;
        };
        /** @description Parser output before hold (no id/status yet). */
        ParsedSlot: {
            resource_type: components["schemas"]["ResourceType"];
            /** @example stage-3 */
            resource_id: string;
            /**
             * Format: date-time
             * @example 2026-09-06T06:00:00Z
             */
            start: string;
            /**
             * Format: date-time
             * @example 2026-09-06T18:00:00Z
             */
            end: string;
        };
        /** @description Ranked alternative offered on collision; also the reroute target. */
        AlternativeSlot: {
            /** @example stage-2 */
            resource_id: string;
            resource_type?: components["schemas"]["ResourceType"];
            /**
             * Format: date-time
             * @example 2026-09-06T06:00:00Z
             */
            start: string;
            /**
             * Format: date-time
             * @example 2026-09-06T18:00:00Z
             */
            end: string;
        };
        Conflict: {
            /** @example stage-3 */
            resource_id: string;
            /**
             * @description Human HH:MM-HH:MM overlap window on the requested date
             * @example 08:00-10:00
             */
            overlap: string;
            /**
             * @description Request id currently holding the overlapping interval
             * @example req_atlas
             */
            blockedBy: string;
        };
        Alternative: {
            slot: components["schemas"]["AlternativeSlot"];
            /** @example 0.95 */
            score: number;
            /** @example Same size, free */
            reason?: string;
        };
        ParsedResult: {
            slots: components["schemas"]["ParsedSlot"][];
            /** @example 0.92 */
            confidence: number;
        };
        CollisionReport: {
            /** @example true */
            hasConflict: boolean;
            conflicts: components["schemas"]["Conflict"][];
            alternatives: components["schemas"]["Alternative"][];
        };
        CreateRequestRequest: {
            /**
             * @description Natural-language request. Inputs >500 chars SHOULD yield 422 NEEDS_CLARIFICATION (truncate + clarify, E02). Empty/whitespace yields 422 (E01).
             * @example Stage 3 tomorrow 6am-6pm, Alexa 65, Maya 2-4pm
             */
            text: string;
            /**
             * Format: uuid
             * @description UUID v4 per submit; stored 24h
             * @example 123e4567-e89b-42d3-a456-426614174000
             */
            idempotencyKey: string;
            /**
             * Format: date-time
             * @description Client clock (UTC ISO) for resolving "tomorrow" etc.
             * @example 2026-09-06T00:00:00Z
             */
            now: string;
        };
        CreateRequestResponse: {
            /** @example req_123 */
            requestId: string;
            parsed: components["schemas"]["ParsedResult"];
            collision: components["schemas"]["CollisionReport"];
            /** @example trace_abc123 */
            traceId: string;
        };
        RerouteRequest: {
            /** @example req_123 */
            requestId: string;
            alternative: components["schemas"]["AlternativeSlot"];
            /**
             * Format: uuid
             * @example 123e4567-e89b-42d3-a456-426614174001
             */
            idempotencyKey: string;
        };
        RerouteResponse: {
            /**
             * @example confirmed
             * @enum {string}
             */
            status: "confirmed";
            slots: components["schemas"]["Slot"][];
            /** @example trace_abc123 */
            traceId: string;
        };
        SlotsResponse: {
            /**
             * Format: date
             * @example 2026-09-06
             */
            date: string;
            slots: components["schemas"]["Slot"][];
            /** @example W/"abc123" */
            etag: string;
        };
        SlotConfirmedEvent: {
            /** @example slot_abc123 */
            slotId: string;
            /** @example trace_abc123 */
            traceId: string;
            /** @example stage-2 */
            resource_id: string;
        };
        CollisionEvent: {
            /** @example req_123 */
            requestId: string;
            conflicts: components["schemas"]["Conflict"][];
        };
        IdempotentReplayError: {
            /** @enum {string} */
            code: "IDEMPOTENT_REPLAY";
            /** @example req_123 */
            requestId: string;
            /** @example Same idempotencyKey already processed */
            message?: string;
        };
        NeedsClarificationError: {
            /** @enum {string} */
            code: "NEEDS_CLARIFICATION";
            /** @example date */
            field: string;
            /** @example Did you mean 2026-09-06? */
            message: string;
        };
        StaleAlternativeError: {
            /** @enum {string} */
            code: "STALE_ALTERNATIVE";
            /** @example Alternative already taken; refreshed alternatives available */
            message: string;
        };
        InvalidIntervalError: {
            /** @enum {string} */
            code: "INVALID_INTERVAL";
            /** @example end must be after start and >= 15 minutes */
            message: string;
        };
        IdempotencyKeyReuseError: {
            /** @enum {string} */
            code: "IDEMPOTENCY_KEY_REUSE";
            /** @example idempotencyKey already used with a different body */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequestRequest"];
            };
        };
        responses: {
            /** @description Parsed + collision report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRequestResponse"];
                };
            };
            /** @description Idempotent replay of a previously seen key (same body) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdempotentReplayError"];
                };
            };
            /** @description Needs clarification, invalid interval, or key reuse */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedsClarificationError"] | components["schemas"]["InvalidIntervalError"] | components["schemas"]["IdempotencyKeyReuseError"];
                };
            };
        };
    };
    rerouteRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerouteRequest"];
            };
        };
        responses: {
            /** @description Reroute confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerouteResponse"];
                };
            };
            /** @description Alternative went stale between check and hold */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaleAlternativeError"];
                };
            };
            /** @description Key reuse with different body, or invalid interval */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdempotencyKeyReuseError"] | components["schemas"]["InvalidIntervalError"];
                };
            };
        };
    };
    listSlots: {
        parameters: {
            query: {
                /** @description Calendar date (YYYY-MM-DD), e.g. 2026-09-06 */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Slots for the date plus ETag for caching */
            200: {
                headers: {
                    /** @description Weak/strong entity tag mirroring body `etag` */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
            /** @description Invalid date or interval */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidIntervalError"];
                };
            };
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
